config/routes.rb
Regnum::Application.routes.draw do
  
  match '/' => 'search#index', via: :get
  match '/logout' => 'accounts#logout', :as => :logout, via: [:get, :post]
  match '/login' => 'accounts#login', :as => :login, via: :get
  match '/authenticate' => 'accounts#authenticate', :as => :authenticate, via: :post
  match '/signup' => 'accounts#new', :as => :signup, via: :get

  match '/mysubmission_show' => 'my_submission#show', :as => :mysubmission, via: :get
  #name conflict:
  # match '/admin_show' => 'admin#show', :as => :admin, via: :get
  match '/new_submission' => 'my_submission#new', :as => :new_submission, via: :get
  match '/create_submission' => 'my_submission#new', :as => :create_submission, via: :get
  #don't see this anywhere
  # match '/accepted' => 'my_submission#accepted', :as => :accepted
  match '/cladename' => 'my_submission#cladename', :as => :cladename, via: [:get, :post]
  match '/save' => 'my_submission#save', :as => :save, via: :post
  match '/create' => 'my_submission#create', as: 'create', via: :post
  
  match '/faq' => 'application#faq', :as => :faq, via: :get
  match '/help' => 'accounts#help', :as => :help, via: :get

  match '/search' => 'search#index', :as => :search, via: :get
  match '/search/:id' => 'search#show', :as => :show, via: :get
  match '/search_res' => 'search#search_res', :as => :search_res, via: :get

  match '/save_submission' => 'my_submission#save_submission', as: :save_submission, via: [:post,:put]
  match '/name/:id' => 'cladename#find_name', :as => :name, via: :get

  match '/my_submission' => 'my_submission#index', :as => :my_submission, via: :get
  match '/my_submission/new' => 'my_submission#new', :as => :new, via: :get
  match '/my_submission/check_name' => 'my_submission#check_name', :as => :check_name, via: :get
  match '/my_submission/template' => 'my_submission#template', :as => :template, via: :get
  match '/my_submission/add_attachment' => 'my_submission#add_attachment', :as => :add_attachment, via: :post
  match '/my_submission/view_attachment/:id' => 'my_submission#view_attachment', :as => :view_attachment, via: :get
  match '/my_submission/remove_attachment/:id' => 'my_submission#remove_attachment', :as => :remove_attachment, via: :get
  match '/my_submission/delete/:id' => 'my_submission#delete', :as => :delete, via: :delete
  #this one comes last so my_submission method calls can pass
  match '/my_submission/:id' => 'my_submission#show', :as => :show_my_submission, via: :get
  match '/templates/load' => 'templates#load', :as => :load_template, via: :get
  #
  match '/admin' => 'admin#index', :as => :admin, via: :get
  match '/admin/add_user' => 'admin#add_user', :as => :add_user_admin, via: :get
  #
  # match '/admin/users/:id' => 'admin#index', via: :get
  match '/admin/users/:id' => 'admin#edit_user', via: [:get,:put,:delete]
  match '/admin/update_user/:id' => 'admin#update_user', :as => :update_user, via: :patch
  #
  match '/phenotypes' => 'phenotypes#index', :as => :phenotypes, via: :get
  match '/phenotypes/create' => 'phenotypes#create', via: :post
  match '/phenotypes/import_ontologies' => 'phenotypes#import_ontologies', via: :post
  #match '/phenotypes/new/:state_id' => 'phenotypes#new'
  match '/phenotypes/new' => 'phenotypes#new', via: :get
  match '/phenotypes/get_form_fields' => 'phenotypes#get_form_fields', via: :get

  match '/characters/new' => 'phenotypes#new_character', via: :get
  match '/characters/create_character' => 'phenotypes#create_character', via: :post
  match '/characters/destroy_character' => 'phenotypes#destroy_character', via: :post
  match '/characters/destroy_state' => 'phenotypes#destroy_state', via: :post
  match '/characters/destroy_phenotype' => 'phenotypes#destroy_phenotype', via: :post
  match '/characters/:character_id/states/new' => 'phenotypes#new_state', via: :get
  match '/characters/:character_id/states' => 'phenotypes#create_state' , :via => [:post]

  match '/ontologies/auto_complete_terms' => 'ontologies#auto_complete_terms', via: :get
  resources :accounts
  resources :submissions do
    collection do
      get :export
      get :export_json
      get :crown_specifiers
    end
  end

  #match '/:controller(/:action(/:id))'
end

app/controllers/submissions_controller.rb
require 'will_paginate/array'

class SubmissionsController < ApplicationController

  before_filter :requires_a_editor_or_admin

  def index
    @subs = submissions_for_editor(params)
    if request.xhr?
      render :partial => 'submissions/submissions_table', :layout => false
    end
  end

  def show
    @sub   = Submission.find(params[:id])
    @stats = StatusChange.where(:submission_id => params[:id]).order('changed_at DESC')
    if request.xhr?
      render :json => @sub
    end
    # redirect_to controller: :my_submission, action: :show
  end

  def crown_specifiers
    @subs = Submission.crown_specifiers
    render :json => @subs
  end

  def edit
    @sub   = Submission.find(params[:id])
    @stats = StatusChange.where(:submission_id => params[:id]).order('changed_at DESC')

    respond_to do |format|
      format.html { render 'cladename/new' }
      format.json { render :json => @sub }
    end
  end

  def destroy
    Submission.delete(params[:id])
    SubmissionCitationAttachment.delete_all(["submission_id = ?", params[:id]])
    #request.xhr? ? head :ok : redirect_to :action => :index
    @subs = submissions_for_editor(params)
    if request.xhr?
      render :partial => 'submissions/submissions_table', :layout => false
    else
      redirect_to :action => :index
    end
  end


  def update
    @sub = Submission.find(params[:id])
    if (@sub.status_id == params[:status].to_i)
      flash[:notice] = "You must change the status to leave an editor comment."
      redirect_to action: :show
      return
    end
    @sub.status_id       = params[:status]
    @sub.status_comments = params[:editor_comments]
    @sub.save
    flash[:notice] = "Submission #{@sub.name} updated."
    #send email
    #StatusMailer.status_change(current_user, sub).deliver
    if request.xhr?
      index
    else
      redirect_to action: :show
    end
  end

  def export_json
    send_data Submission.all.map { |sub|
      if (sub.clade_type == Submission::CrownBasedTotalClade)
        sub.specifiers = sub.specifiers.select { |spec| spec["specifier_type"] == "crown" }
      end
      sub
    }.to_json,
              :type        => 'application/json',
              :disposition => "attachment",
              :filename    => "regnum_submissions.json"
  end

  def export
    require 'csv'
    csv_string = CSV.generate do |csv|
      csv << ["registration number", "clade name"]
      Submission.all.each { |submission| csv << [submission.registration_number, submission.name] }
    end
    send_data(csv_string,
              :type        => 'text/csv; charset=utf-8; header=present',
              :disposition => "attachment",
              :filename    => "regnum_cladenames_with_registration_number.csv")
  end

  private

  #gets right set of subs depending of type of editor/admin
  def submissions_for_editor(params)
    params[:term]       ||= ''
    params[:page]       ||= '1'
    params[:order]      ||= 'name'
    params[:dir]        ||= 'up'
    params[:clade_type] ||= 'all'

    dir  = params[:dir] == 'up' ? 'ASC' : 'DESC'
    subs = if current_user.is_admin?
             Submission.where("name LIKE ?", "%#{params[:term]}%") #admin sees all :)
           elsif current_user.is_reviewer?
             Submission.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "%#{params[:term]}%")
           elsif current_user.is_opt_out_reviewer?
             Submission.opt_out.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "%#{params[:term]}%")
           elsif current_user.is_opt_in_reviewer?
             Submission.opt_in.where("status_id > ? AND name LIKE ?", Status.find_by_status('unsubmitted').id, "%#{params[:term]}%")
           end.order("#{params[:order]} #{dir}")

    if params[:order] == "submitted_at"
      subs = subs.sort do |a,b|
          dir == "ASC" ? a.submitted_at <=> b.submitted_at : b.submitted_at <=> a.submitted_at
      end
    end
    subs = subs.paginate(:page => params[:page], :per_page => 12)
    return params[:clade_type] == 'all' ? subs : subs.where("clade_type = ?", params[:clade_type])
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper

  def name_string_formatted
    if @sub.name_string.nil?
      return ""
    end
    raw @sub.name_string.sub(@sub.name, "<em>#{@sub.name}</em>")
  end

  def abbreviation_formatted
    abv = @sub.abbreviation
    @sub.specifiers.each do |spec|
      sn = spec[:specifier_name]
      abv.sub!(sn, "<em>#{sn}</em>")
    end
    abv.sub!("TODO: finalize definition","")
    raw abv
  end

  def verbatim_definition
    definition = @sub.definition
    if definition.nil?
      return ""
    end
    @sub.specifiers
        .map { |sv| sv[:specifier_name] }
        .each { |spec_name| definition.gsub!(/#{spec_name}/i, '<em>\0</em>') }
    raw definition
  end

  def crown_specifiers_select_tag
    select_tag("crown_specifier",
               options_from_collection_for_select(Submission.crown_specifiers, :name_id, :name_and_clade_type),
               include_blank: "Please make a selection",
               data: { bind: "value: specifier_crown" })
  end
end

app/views/submissions/_submissions_table.html.haml
.sortable-table-div
  = render :partial => 'shared/sortable_table_loading_message'
  %table#user_submissions_table.sortable-table
    %tr.sortable-table-header-row
      %th.sortable.table-header-link=table_sort_header('name')
      %th.sortable.table-header-link=table_sort_header('clade_type', 'Type')
      %th.sortable.table-header-link=table_sort_header('submitted_by', 'Submitter')
      %th.sortable.table-header-link=table_sort_header('submitted_at', 'Submission status')
      %th{:colspan => 3}
    %tbody
      -@subs.each do |sub|
        %tr{:class => cycle('odd-row','even-row'), :id => sub.id, :title => "click to open submission"  }
          %td= sub.name
          %td= sub.clade_type
          %td{ :style => 'width:180px'}= sub.user.nil? ? "" : sub.user.last_name + ', ' + sub.user.first_name
          %td{ :style => 'width:180px'}= sub.submitted_at
          %td{ :style => 'width:40px'}
            =form_for sub, :url => submission_path(sub.id), :html => {:method => :get } do |s|
              %input.submit_button{:type => 'submit', :value => 'review'} 
          -if current_user.is_admin? 
            %td{:style => 'width:40px'}
              = link_to "Edit", "/submissions/" + sub.id.to_s + "/edit", class: "button"
          %td{ :style => 'width:40px'}
            =form_for sub, :url => submission_path(sub.id), :html => {:method => :delete } do |s|
              %button.submit_button{:type => 'submit', :title => 'click to delete'} Delete
      %tr
        %td{:colspan => 5, :style => 'text-align:center;padding:1px;border:none;'}
          =will_paginate @subs, renderer: RemoteLinkRenderer,:params => {:controller => :submissions, :action => nil}
      %tr
        %td{:colspan => 5, :style => 'text-align:center;padding:1px;border:none;'}
          =page_entries_info @subs, {:model => 'clade names'}

app/views/submissions/index.html.haml
.content_box{:style => 'margin:20px auto; max-width:390px;'}
  %form{:action => '/submissions', :method => :get, :style => 'display: inline-block;' }
    = render :partial => 'shared/submissions_search_inputs'
#submissions_table_div.sortable-table-holder
  = render :partial => 'submissions/submissions_table'

app/views/submissions/show.html.haml
.submission-holder
  =render :partial => 'shared/status_change_list'
.submission-holder
  %h1{style:"margin-top:1em;margin-bottom:1em;"} Submission:
.submission-holder
  =render :partial => 'shared/cladename_view'
.submission-holder
  %h1{style:"margin-top:1em;margin-bottom:1em;"} Editor comments and approval:
.editor-box
  =form_for @sub, :url => '/submissions/'+@sub.id.to_s, :method => :put do |s|
    %table{style: "width:100%"}
      %tr
        %td.name
          %p Status:
        %td{:style => 'text-align:right;'}
          %input{:type => 'submit', :value => 'Save', :id => 'sub_save_button'}
      %tr
        %td
          %select{:name => 'status'}
            = options_from_collection_for_select Status.all, :status_id, :status, @sub.status_id
      %tr
        %td.name{:colspan => '2' }
          %p Editor Comments:
      %tr
        %td{:colspan => '2'}
          %textarea{ :name => 'editor_comments', :rows => 5, :style => "width: 100%"}